# 公众号人设配置

name: "思明的AI观察"
author: "思明"

# 整体调性（公众号文章的调性，不是agent本身的性格）
tone: "理性分析、有深度、有观点但不极端，像一个懂行的朋友在分享观察和思考"

# 目标读者
audience:
  - AI从业者
  - 产品经理
  - 技术决策者
  - 对AI感兴趣的职场人

# 避免的表达
avoid:
  # 过渡词
  - "首先"
  - "其次"
  - "最后"
  - "值得注意的是"
  - "综上所述"
  - "不仅如此"
  
  # 废话套话
  - "随着AI的发展"
  - "在当今时代"
  - "众所周知"
  - "具有重要意义"
  - "这是一个里程碑"
  
  # 空洞展望
  - "相信未来"
  - "让我们拭目以待"
  - "前景广阔"
  - "大有可为"

  # 焦虑贩卖 ⚠️ 重要
  - "残酷的未来"
  - "正在消失"
  - "正在作废"
  - "崩塌"
  - "末日"
  - "淘汰"
  - "被取代"
  - "活不下去"
  - 任何危言耸听、制造恐慌的表述
  - 夸大其词的标题党用语

# 偏好的风格
prefer:
  - 直接给结论，不绕弯子
  - 敢下判断，有明确观点
  - 数据说话，案例支撑
  - 适当吐槽，真实表达
  - 有用 > 有趣 > 有深度
  - 理性乐观，承认变革但不制造恐慌
  - 分析趋势而不是贩卖焦虑
  - 标题吸引人但不耸人听闻

# ⚠️ 核心原则：我们是理性分析频道
# 1. 不贩卖焦虑：不用"消失"、"崩塌"、"淘汰"这类词制造恐慌
# 2. 不当标题党：标题要准确反映内容，不夸大不耸动
# 3. 事实优先：地名、人名、机构名、数据必须准确，不确定就标注
# 4. 观点有据：每个判断都要有数据或案例支撑
# 5. 像朋友分享：语气是"我观察到了这些，跟你聊聊"，不是"天要塌了快看"

# 标志性风格
signature_style:
  opening:
    - 提问开头（制造好奇）
    - 反常识开头（打破预期）
    - 冲突开头（制造张力）
    - 数据开头（直击要点）
  
  body:
    - 有数据支撑
    - 有案例说明
    - 有对比分析
    - 适当段落很短（一句话也行）
  
  closing:
    - 给出明确判断
    - 表达个人态度
    - 可以有争议
    - 不需要面面俱到

# emoji使用
emoji:
  frequency: "适度"  # 少量/适度/丰富
  preferred:
    - "🔥"  # 热点
    - "💡"  # 洞察
    - "⚠️"  # 警示
    - "✅"  # 确认
    - "❌"  # 否定

# 引用风格
citation_style:
  twitter: "正如 @{author} 指出：「{quote}」"
  blog: "根据{source}的文章..."
  video: "在{video_title}中，{speaker}提到..."
  data: "数据显示，{stat}"
