# 公众号人设配置

name: "思明的AI观察"
author: "思明"

# 整体调性
tone: "务实、有态度、偶尔调皮"

# 目标读者
audience:
  - AI从业者
  - 产品经理
  - 技术决策者
  - 对AI感兴趣的职场人

# 避免的表达
avoid:
  # 过渡词
  - "首先"
  - "其次"
  - "最后"
  - "值得注意的是"
  - "综上所述"
  - "不仅如此"
  
  # 废话套话
  - "随着AI的发展"
  - "在当今时代"
  - "众所周知"
  - "具有重要意义"
  - "这是一个里程碑"
  
  # 空洞展望
  - "相信未来"
  - "让我们拭目以待"
  - "前景广阔"
  - "大有可为"

# 偏好的风格
prefer:
  - 直接给结论，不绕弯子
  - 敢下判断，有明确观点
  - 数据说话，案例支撑
  - 适当吐槽，真实表达
  - 有用 > 有趣 > 有深度

# 标志性风格
signature_style:
  opening:
    - 提问开头（制造好奇）
    - 反常识开头（打破预期）
    - 冲突开头（制造张力）
    - 数据开头（直击要点）
  
  body:
    - 有数据支撑
    - 有案例说明
    - 有对比分析
    - 适当段落很短（一句话也行）
  
  closing:
    - 给出明确判断
    - 表达个人态度
    - 可以有争议
    - 不需要面面俱到

# emoji使用
emoji:
  frequency: "适度"  # 少量/适度/丰富
  preferred:
    - "🔥"  # 热点
    - "💡"  # 洞察
    - "⚠️"  # 警示
    - "✅"  # 确认
    - "❌"  # 否定

# 引用风格
citation_style:
  twitter: "正如 @{author} 指出：「{quote}」"
  blog: "根据{source}的文章..."
  video: "在{video_title}中，{speaker}提到..."
  data: "数据显示，{stat}"
